#:schema node_modules/wrangler/config-schema.json
name = "sub-cleaner"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "91cef44d275545d5992cf396603b47cc" }
]

[assets]
directory = "./public"
